---
- name: Ensure hardware virtualisation is supported
  shell:
    cmd: test $(egrep -c '(vmx|svm)' /proc/cpuinfo) -gt 0
- block:
  - name: Ensure KVM is installed
    package:
      name:
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils
        - cpu-checker
  - name: Ensure users are added to kvm and libvirt groups
    user:
      name: "{{ kvm_user }}"
      append: true
      groups: kvm, libvirt
    loop: "{{ kvm_users }}"
    loop_control:
      loop_var: kvm_user
  become: yes
