---
- name: Ensure Vagrant is installed
  package: name=vagrant state=present
  become: yes
- name: Ensure Vagrant Libvirt provider in installed on Linux
  package: name=vagrant-libvirt state=present
  when: ansible_system == "Linux"
