---
- block: # Install VirtualBox on non- macOS hosts with privileged operations
  - block: # Debian family
    - name: Ensure VirtualBox dependencies are installed
      package: name=openssl state=present
    - name: Ensure Oracle's official GPG key is installed
      shell: |
        if [ ! -f /usr/share/keyrings/oracle-virtualbox-2016.gpg ]; then
          curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
        fi
      args:
        creates: /usr/share/keyrings/oracle-virtualbox-2016.gpg
    - block: # Devuan
      - name: Get Debian version
        shell: cat /etc/debian_version | sed 's/^\([0-9][0-9]*\)\..*$/\1/'
        register: debian_version
        when: ansible_distribution_file_variety == "Debian"
      - name: Get Debian codename
        set_fact:
          debian_codename: "{{ codenames[debian_version.stdout_lines[0]] }}"
        vars:
          codenames: "{{ [
            {'version': '14', 'codename': 'forky'},
            {'version': '13', 'codename': 'trixie'},
            {'version': '12', 'codename': 'bookworm'},
            {'version': '11', 'codename': 'bullseye'},
            {'version': '10', 'codename': 'buster'},
            {'version': '9', 'codename': 'stretch'},
            {'version': '8', 'codename': 'jessie'}
          ]| items2dict(key_name='version', value_name='codename')}}"
      - name: Ensure VirtualBox repo is registered on Devuan
        apt_repository:
          repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/{{ ansible_os_family | lower }} {{ debian_codename }} contrib"
          filename: virtualbox
      when: ansible_distribution == 'Devuan'
    - name: Ensure VirtualBox repo is registered on Debian family
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/{{ ansible_os_family | lower }} {{ ansible_lsb.codename }} contrib"
        filename: virtualbox
      when: ansible_distribution != 'Devuan'
    when: ansible_os_family == 'Debian'
  - block: # Red Had family
    - name: Ensure kernel headers are installed on Red Hat hosts
      package: name="kernel-devel-{{ ansible_kernel }}"
    - name: Ensure Oracle GPG key is installed on Red Hat hosts
      rpm_key: key=https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: Ensure VirtualBox repository is installed on Fedora
      command:
        cmd: dnf config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
        creates: /etc/yum.repos.d/virtualbox.repo
    when: ansible_os_family == 'RedHat'
  - name: Ensure VirtualBox is installed
    package: name={{ virtualbox_package[ansible_os_family]}}
    vars:
      virtualbox_package: "{{ [
        {'os_family': 'Debian', 'package': 'virtualbox-7.0'},
        {'os_family': 'RedHat', 'package': 'VirtualBox-7.0'},
        {'os_family': 'Archlinux', 'package': 'virtualbox'},
        {'os_family': 'Artix Linux', 'package': 'virtualbox'},
        {'os_family': 'FreeBSD', 'package': 'virtualbox-ose'}
      ]| items2dict(key_name='os_family', value_name='package')}}"
    register: virtualbox_install_test
  - name: Ensure VirtualBox kernel modules are compiled on non- Arch Linux hosts
    command:
      cmd: /sbin/vboxconfig
      creates: "/usr/lib/modules/{{ ansible_kernel }}/misc/vboxdrv.ko"
    when: "ansible_system == 'Linux' and ansible_os_family not in ['Archlinux', 'Artix Linux']"
  when: ansible_system != 'Darwin'
  become: true
- name: Ensure VirtualBox is installed on macOS hosts
  homebrew_cask:
    name: virtualbox
    sudo_password: "{{ ansible_become_pass }}"
  register: virtualbox_install_test
  when: ansible_system == 'Darwin'
- name: Test if VirtualBox is installed
  set_fact:
    virtualbox_installed: true
  changed_when: virtualbox_install_test.failed == false
