---
- block:
  - block:
    - name: Ensure VirtualBox dependencies are installed
      package: name=openssl state=present
    - name: Ensure Oracle's official GPG key is installed
      shell: |
        if [ ! -f /usr/share/keyrings/oracle-virtualbox-2016.gpg ]; then
          curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
        fi
      args:
        creates: /usr/share/keyrings/oracle-virtualbox-2016.gpg
    - block:
      - name: Get Debian version
        shell: cat /etc/debian_version | sed 's/^\([0-9][0-9]*\)\..*$/\1/'
        register: debian_version
        when: ansible_distribution_file_variety == "Debian"
      - name: Get Debian codename
        set_fact:
          debian_codename: "{{ codenames[debian_version.stdout_lines[0]] }}"
        vars:
          codenames: "{{ [
            {'version': '14', 'codename': 'forky'},
            {'version': '13', 'codename': 'trixie'},
            {'version': '12', 'codename': 'bookworm'},
            {'version': '11', 'codename': 'bullseye'},
            {'version': '10', 'codename': 'buster'},
            {'version': '9', 'codename': 'stretch'},
            {'version': '8', 'codename': 'jessie'}
          ]| items2dict(key_name='version', value_name='codename')}}"
      - name: Ensure VirtualBox repo is registered on Devuan
        apt_repository:
          repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/{{ ansible_os_family | lower }} {{ debian_codename }} contrib"
          filename: virtualbox
      when: ansible_distribution == 'Devuan'
    - name: Ensure VirtualBox repo is registered on Debian family
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/{{ ansible_os_family | lower }} {{ ansible_lsb.codename }} contrib"
        filename: virtualbox
      when: ansible_distribution != 'Devuan'
    when: ansible_os_family == "Debian"
  - name: Ensure VirtualBox is installed
    package: name=virtualbox-7.0 state=present
  become: yes
