---
- block: # browser is defined
  - name: Install Chromium browser
    include_tasks: chromium.yml
    when: "'chromium' in browsers"
  - name: Install Google Chrome
    include_tasks: chrome.yml
    when: "'chrome' in browsers"
  - name: Ensure web browser is installed
    package: name={{ item }} state=present
    with_items:
      "{{ browsers | difference(['chrome', 'chromium', 'edge', 'firefox']) | list }}"
    become: "{{ false_for_macos }}"
  - name: Install non snap version of Firefox
    include_tasks: firefox.yml
    when: "'firefox' in browsers"
  - name: Ensure Microsoft Edge is installed on macOS hosts
    homebrew_cask:
      name: microsoft-edge
      sudo_password: "{{ ansible_become_pass }}"
    when: "'edge' in browsers and ansible_system == 'Darwin'"
  when: browsers is defined
