---
- name: Ensure Chromium browser is installed on Arch Linux hosts
  kewlfft.aur.aur: name=chromium-snapshot-bin
  when: "ansible_os_family in ['Archlinux', 'Artix Linux']"
- name: Ensure Chromium browser is installed on non- Arch Linux hosts
  package: name=chromium
  when: "ansible_os_family not in ['Archlinux', 'Artix Linux']"
  become: true
