---
- name: Set up Cinnamon
  include_tasks: cinnamon.yml
  when: desktops is defined and 'cinnamon' in desktops
- name: Set up dwm
  include_tasks: dwm.yml
  when: desktops is defined and 'dwm' in desktops
- name: Set up kde
  include_tasks: kde.yml
  when: desktops is defined and 'kde' in desktops
- name: Set up Xfce
  include_tasks: xfce.yml
  when: desktops is defined and 'xfce' in desktops
- block:
  - name: Ensure Desktop Environment is installed
    package: name={{ desktops | difference(['cinnamon', 'dwm', 'kde', 'xfce']) | list }}
    when: desktops is defined
  - name: Ensure mail client is installed
    package: name={{ mailers }} state=present
    when: mailers is defined
  - name: Ensure fonts are installed
    package: name={{ fonts }} state=present
    when: fonts is defined
  become: "{{ false_for_macos }}"
- name: Install web browsers
  include_tasks: browser.yml
  when: browsers is defined
