---
- name: Bootstrap for macOS target host
  include_tasks: macos.yml
  when: ansible_system == 'Darwin'
- name: Bootstrap for Windows target host
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
- block:
  - name: Ensure groups exist on the target host
    group:
      name: "{{ item.name }}"
    with_items:
      - "{{ groups_to_create }}"
    when: groups_to_create is defined
  - block: # users_to_create is defined
    - name: Ensure users exist on the target host
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
        password_lock: "{{ item.password_lock | default(false) }}"
        group: "{{ item.group | default(omit) }}"
        groups: "{{ item.groups | default(omit) }}"
        append: "{{ item.append | default(false) }}"
        generate_ssh_key: "{{ item.ssh_key.generate | default(false) }}"
        ssh_key_bits: "{{ item.ssh_key.bits | default(omit) }}"
        ssh_key_comment: "{{ item.ssh_key.comment | default(omit) }}"
        ssh_key_passphrase: "{{ item.ssh_key.passphrase | default(omit) }}"
        ssh_key_type: "{{ item.ssh_key.type | default(omit) }}"
        force: "{{ item.ssh_key.replace | default(false) }}"
        shell: "{{ item.shell | default(omit) }}"
      with_items:
        - "{{ users_to_create }}"
    - name: Prepare authorized keys for each user
      set_fact:
        # This creates a list of strings where each string is "[options] key] [comment]"
        user_key_list: "{% for k in item.authorized_keys['keys'] -%}{{ [k.options | default(''), k.key, k.comment | default('')] | select('string') | select('ne', '') | join(' ') }}{% if not loop.last %}{% raw %}\n{% endraw %}{% endif %}{%- endfor %}"
      loop: "{{ users_to_create }}"
      loop_control:
        loop_var: item  # Use a custom loop variable to avoid conflict if needed
      when:
        - item.authorized_keys is defined
        - item.authorized_keys.keys is defined
    - name: Apply authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ user_key_list }}"  # keys concatenated with '\n' delimiter
        exclusive: "{{ item.authorized_keys.exclusive | default(false) }}"
        state: present
      loop: "{{ users_to_create }}"
      when:
        - item.authorized_keys is defined
        - item.authorized_keys.keys is defined
    - name: Install cron jobs
      cron:
        user: "{{ item[0].name }}"
        name: "{{ item[1].name }}"
        minute: "{{ item[1].minute }}"
        hour: "{{ item[1].hour }}"
        day: "{{ item[1].day }}"
        month: "{{ item[1].month }}"
        weekday: "{{ item[1].day_of_week }}"
        job: "{{ item[1].job }}"
      loop: "{{ users_to_create | subelements('cron.jobs', skip_missing=true) }}"
      loop_control:
        label: "{{ item[0].name }} -> {{ item[1].name }}"
      when:
        - item[0].cron is defined
        - item[0].cron.jobs is defined
    - name: Set environmet for cron jobs
      cron:
        user: "{{ item[0].name }}"
        env: true
        name: "{{ item[1] | split('=', 1) | first }}"
        job: "{{ item[1] | split('=', 1) | last }}"
      loop: "{{ users_to_create | subelements('cron.environment_vars', skip_missing=true) }}"
      loop_control:
        label: "{{ item[0].name }} -> {{ item[1] }}"
      when:
        - item[0].cron is defined
        - item[0].cron.environment_vars is defined
  become: true
- name: Set up ZFS on FreeBSD
  include_tasks: zfs_on_freebsd.yml
  when: ansible_system == 'FreeBSD' and (base is defined and 'zfs' in base)
- name: Set up ZFS on Linux
  include_tasks: zfs_on_linux.yml
  when: ansible_system == 'Linux' and (base is defined and 'zfs' in base)
- name: Set up NFS client
  include_tasks: nfs_client.yml
  when: (base is defined and 'nfs_client' in base)
- block: # misc_tools is defined
  - name: Set up miscellaneous tools
    package: name="{{ item }}" state=present
    with_items:
      - "{{ misc_tools | list }}"
    become: "{{ false_for_macos_and_windows }}"
  when: misc_tools is defined
- name: Set up miscellaneous GUI tools on macOS
  homebrew_cask:
    name: "{{ item }}"
    sudo_password: "{{ ansible_become_pass }}"
  with_items:
    - "{{ misc_gui_tools | list }}"
  when: misc_gui_tools is defined and ansible_system == 'Darwin'
  become: "{{ false_for_macos_and_windows }}"
- name: Ensure basic configuration is made on Arch Linux
  include_tasks: archlinux.yml
  when: "ansible_os_family in ['Archlinux', 'Artix Linux']"
- block: # Set hostname
  - name: Ensure hostname is set
    hostname: name="{{ base.hostname }}"
    when: ansible_os_family != 'Windows'
    become: true
  - name: Ensure hostname is set on Windows hosts
    ansible.windows.win_hostname:
      name: "{{ base.hostname }}"
    notify: hostname has been changed
    when: ansible_os_family == 'Windows'
  when: base is defined and base.hostname is defined
