---
- name: restart WireGuard service on macOS
  community.general.launchd:
    name: com.wireguard.wg0
    enabled: yes
    state: restarted
  become: true

- name: restart WireGuard service on OpenBSD
  command: sh /etc/netstart
  when: wireguard['start_at_boot'] is defined and wireguard['start_at_boot'] == true
  become: true

- name: restart WireGuard service
  service:
    name: "{{ service_names[ansible_service_mgr] }}"
    enabled: yes
    state: restarted
  vars:
    service_names: "{{ [
      {'service_mgr': 'systemd', 'service_name': 'wg-quick@wg0'},
      {'service_mgr': 'sysvinit', 'service_name': 'wg0'},
     ] | items2dict(key_name='service_mgr', value_name='service_name') }}"
  when: wireguard['start_at_boot'] is defined and wireguard['start_at_boot'] == true and ansible_distribution not in ['OpenBSD']
  become: true
