---
- name: Ensure Claude Code installer is pushed
  template: src=install_claude_code.sh.j2 dest=/tmp/install_claude_code.sh mode=0755
- name: Ensure Claude Code is installed
  shell:
    cmd: /tmp/install_claude_code.sh
  become: true
  become_user: "{{ target_user }}"
