---
- block: # Need privileged operations on Debian hosts
  - name: Ensure old Docker version is uninstalled
    ansible.builtin.package:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
  - name: Ensure Docker Engine dependencies are installed
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
      update_cache: true
  - name: Ensure Keyring directory is created
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755
  - name: Ensure Docker's official GPG key is installed
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower | replace('devuan', 'debian') }}/gpg"
      dest: /etc/apt/keyrings/docker.asc
      mode: a+r
  - block: # Determine Devuan codename
    - name: Get Debian version
      ansible.builtin.shell: cat /etc/debian_version | sed 's/^\([0-9][0-9]*\)\..*$/\1/'
      register: debian_version
      when: ansible_distribution_file_variety == "Debian"
      check_mode: false
    - name: Ensure Docker repo is registered on Devuan
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codenames[ansible_lsb.codename] }} stable"
        filename: docker
      vars:
          codenames: "{{ [
            {'devuan_codename': 'excalibur', 'debian_codename': 'trixie'},
            {'devuan_codename': 'daedalus', 'debian_codename': 'bookworm'},
            {'devuan_codename': 'chimaera', 'debian_codename': 'bullseye'},
            {'devuan_codename': 'beowulf', 'debian_codename': 'buster'},
            {'devuan_codename': 'ascii', 'debian_codename': 'stretch'},
            {'devuan_codename': 'jessie', 'debian_codename': 'jessie'}
          ]| items2dict(key_name='devuan_codename', value_name='debian_codename')}}"
    when: ansible_distribution == 'Devuan'
  - name: Ensure Docker repository information is added
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
      filename: docker
    when: ansible_distribution != 'Devuan'
  - name: Ensure Docker Engine is installed
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      update_cache: true
  become: true
  when: ansible_os_family == 'Debian'
