---
- block: # Need privileged operations
  - name: Ensure old Docker version is uninstalled
    ansible.builtin.package:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
  - name: Ensure the latest package information is downloaded
    ansible.builtin.command:
      cmd: apt update
  - name: Ensure Docker Engine dependencies are installed
    ansible.builtin.package:
      name:
        - ca-certificates
        - curl
        - gnupg
  - name: Ensure Keyring directory is created
    ansible.builtin.shell: |
      if [ ! -d /etc/apt/keyrings ]; then
        mkdir -m 0755 -p /etc/apt/keyrings
      fi
    args:
      creates: /etc/apt/keyrings
  - name: Ensure Docker's official GPG key is installed
    ansible.builtin.shell: |
      if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
        curl -fsSL https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      fi
    args:
      creates: /etc/apt/keyrings/docker.gpg
  - name: Ensure Docker repository information is added
    ansible.builtin.shell: |
      echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    args:
      creates: /etc/apt/sources.list.d/docker.list
  - name: Ensure the latest package information is downloaded again
    ansible.builtin.command:
      cmd: apt update
  - name: Ensure Docker Engine is installed
    ansible.builtin.package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
  become: true
