---
- name: Ensure development tools are installed on non-Windows hosts
  package: name="{{ item }}"
  with_items:
    - "{{ development_tools | default([]) | difference(['bcompare', 'gcm', 'gh', 'gotd', 'gotwebd', 'java', 'repo', 'vscode']) | list }}"
  become: "{{ false_for_macos }}"
  when: development_tools is defined and ansible_os_family != 'Windows'
- name: Ensure development tools are installed on Windows hosts
  win_chocolatey: name="{{ item }}"
  with_items:
    - "{{ development_tools | default([]) | difference(['bcompare', 'gcm', 'gotd', 'gotwebd', 'java', 'markdown', 'repo']) | list }}"
  when: development_tools is defined and ansible_os_family == 'Windows'
- block: # Need privileged operations
  - block: # Debian family
    - name: Ensure essential build tools are installed on Debian host
      package: name=build-essential
      when: ansible_os_family == 'Debian'
    - block: # development_tools is defined and 'gcm' in development_tools
      - name: Check whether Git Credential Manager is installed
        shell: apt list --installed | grep -q gcm
        ignore_errors: true
        register: gcm_install_test
      - name: Ensure Git Credential Manager dependencies are satisfied
        package:
          name:
          - gpg
          - pass
          - gpg-agent
          - pinentry-tty
        when: ansible_system == "Linux"
      - name: Optionally install Git Credential Manager
        apt:
          deb: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.3.2/gcm-linux_amd64.2.3.2.deb
        when: gcm_install_test.rc != 0
      when: development_tools is defined and 'gcm' in development_tools
    when: ansible_os_family == "Debian"
  - name: Optionally install OpenJDK
    package: name="{{ jdk }}"
    when: development_tools is defined and 'java' in development_tools and ansible_system != "Darwin"
  - name: Optionally install OpenJDK (Eclipse Temurin) on macOS
    homebrew_cask:
      name: "{{ jdk | default('temurin') }}"
      sudo_password: "{{ ansible_become_pass }}"
    when: development_tools is defined and 'java' in development_tools and ansible_system == "Darwin"
  become: "{{ false_for_macos }}"
- name: Install GitHub CLI
  include_tasks: github_cli.yml
  when: development_tools is defined and 'gh' in development_tools and ansible_os_family != 'Windows'
- name: Optionally install Visual Studio Code
  include_tasks: vscode.yml
  when: development_tools is defined and 'vscode' in development_tools and ansible_os_family != 'Windows'
- name: Optionally install repo
  include_tasks: repo.yml
  when: development_tools is defined and 'repo' in development_tools
- name: Install development environment for Android
  include_tasks: android.yml
  when: android_tools is defined
- name: Configure Game of Trees daemon
  include_tasks: got.yml
  when: development_tools is defined and ('gotd' in development_tools or 'gotwebd' in development_tools)
- name: Install Beyond Compare
  include_tasks: bcompare.yml
  when: development_tools is defined and 'bcompare' in development_tools
