---
- block: # Need privileged operations
  - name: Ensure development tools are installed
    package:
      name: "{{ development_tools | default([]) | difference(['gcm', 'gh', 'gotd', 'gotwebd', 'java', 'repo', 'vscode']) | list }}"
  - block:
    - name: Ensure essential build tools are installed on Debian host
      package: name=build-essential
      when: ansible_os_family == 'Debian'
    - block: # development_tools is defined and 'gcm' in development_tools
      - name: Check whether Git Credential Manager is installed
        shell: apt list --installed | grep -q gcm
        ignore_errors: true
        register: gcm_install_test
      - name: Ensure Git Credential Manager dependencies are satisfied
        package:
          name:
          - gpg
          - pass
          - gpg-agent
          - pinentry-tty
        when: ansible_system == "Linux"
      - name: Optionally install Git Credential Manager
        apt:
          deb: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.3.2/gcm-linux_amd64.2.3.2.deb
        when: gcm_install_test.rc != 0
      when: development_tools is defined and 'gcm' in development_tools
    when: ansible_os_family == "Debian"
  - name: Optionally install OpenJDK
    package: name="{{ jdk }}"
    when: development_tools is defined and 'java' in development_tools and ansible_system != "Darwin"
  - name: Optionally install OpenJDK (Eclipse Temurin) on macOS
    homebrew_cask:
      name: "{{ jdk | default('temurin') }}"
      sudo_password: "{{ ansible_become_pass }}"
    when: development_tools is defined and 'java' in development_tools and ansible_system == "Darwin"
  become: "{{ false_for_macos }}"
- name: Install GitHub CLI
  include_tasks: github_cli.yml
  when: development_tools is defined and 'gh' in development_tools
- name: Optionally install Visual Studio Code
  include_tasks: vscode.yml
  when: development_tools is defined and 'vscode' in development_tools
- block: # development_tools is defined and 'repo' in development_tools
  - name: Ensure repo dependencies are satisfied
    package:
      name:
        - curl
        - gnupg
    become: "{{ false_for_macos }}"
  - block:
    - name: Ensure ~/bin directory is created
      file: name=/home/{{ target_user }}/bin state=directory owner={{ target_user }}
    - name: Optionally install repo
      shell: |
        id
        export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
        curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
        gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
        curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} /home/{{ target_user }}/bin/repo && rm -rf ${REPO}
        chown {{ target_user }} /home/{{ target_user }}/bin/repo
      args:
        creates: "/home/{{ target_user }}/bin/repo"
      register: repo_installed
      notify: repo_post_installation_message
    become: true
  when: development_tools is defined and 'repo' in development_tools
- name: Install development environment for Android
  include_tasks: android.yml
  when: android_tools is defined
- name: Configure Game of Trees daemon
  include_tasks: got.yml
  when: development_tools is defined and ('gotd' in development_tools or 'gotwebd' in development_tools)
