---
- block: # development_tools is defined and 'repo' in development_tools
  - name: Ensure repo is installed on Debian family or macOS
    package: name=repo
    become: "{{ false_for_macos }}"
    when: ansible_os_family == 'Debian' or ansible_system == 'Darwin'
  - block: # non- Debian Linux hosts with privileged operations
    - name: Ensure repo dependencies are satisfied
      package:
        name:
          - curl
          - gnupg
    - name: Ensure ~/bin directory is created
      file: name=/home/{{ target_user }}/bin state=directory owner={{ target_user }}
    - name: Optionally install repo
      shell: |
        id
        export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
        curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
        gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
        curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} /home/{{ target_user }}/bin/repo && rm -rf ${REPO}
        chown {{ target_user }} /home/{{ target_user }}/bin/repo
      args:
        creates: "/home/{{ target_user }}/bin/repo"
      register: repo_installed
      notify: repo_post_installation_message
    become: true
    when: ansible_system == 'Linux' and ansible_os_family != 'Debian'
  when: development_tools is defined and 'repo' in development_tools
