---
- block: # Install xrdp
  - name: Ensure xrdp is installed on Arch Linux hosts
    kewlfft.aur.aur: name=xrdp
    when: "ansible_os_family in ['Archlinux', 'Artix Linux']"
  - name: Ensure xrdp is installed on non- Arch Linux hosts
    package: name=xrdp
    when: "ansible_os_family not in ['Archlinux', 'Artix Linux']"
    become: true
  - name: Ensure xrdp is enabled and started
    service: name="{{ item }}" state=started enabled=true
    with_items:
      - xrdp
      - xrdp-sesman
    become: true
  - name: Ensure startwm.sh is installed if supplied for the target hosts
    copy:
      src: "{{ startwm_sh_file }}"
      dest: "/home/{{ item }}/startwm.sh"
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0755'
    vars:
      - params:
        - files:
          - "{{ inventory_hostname }}/startwm.sh"
      - startwm_sh_file: "{{ lookup('first_found', params, errors='ignore') | default('', true) }}"
    when: startwm_sh_file != ''
    become: true
    with_items: "{{ users }}"
  when: remote_access_servers is defined and 'xrdp' in remote_access_servers
- block: # Need privileged operations
  - name: Ensure remote access server components are installed
    package: "name={{ remote_access_servers | reject('search', 'xrdp') | list }}"
  - block: # Post-install configuration of xrdp on Red Hat hosts
    - name: Check whether firewalld is running on Red Hat hosts
      systemd_service: name=firewalld
      register: firewalld_status
    - name: Ensure firewall allows incoming connection to RDP port on Red Hat hosts
      firewalld:
        port: 3389/tcp
        permanent: true
        immediate: true
        state: enabled
      when: firewalld_status.status.ActiveState == 'active'
    when: ansible_os_family == 'RedHat' and (remote_access_servers is defined and 'xrdp' in remote_access_servers)
  become: true
