---
- block:
  - name: Ensure HashiCorp PGP key is installed
    get_url:
      url: https://apt.releases.hashicorp.com/gpg
      dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - name: Ensure Packer repo is registered
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
      filename: hashicorp.list
  - name: Ensure Packer is installed
    package: name=packer state=present
  become: yes
